### ISSUE TITLE
Add to pipy and pip install instructions

### ISSUE THREAD

**Issue by leifdenby** [leifdenby/tephigram_python#4]

**Comment by eliteuser26** [comment]
What is the best way to download your code as a whole like pip install?

**Comment by leifdenby** [comment]
The package can be install with `pip install tephigram` now :)

**Comment by eliteuser26** [comment]
Thanks. This is great. Did you have a chance to integrate into Metpy?

**Comment by leifdenby** [comment]
I'm still working on it. I'm still undecided whether to reuse their parcel integration code include my own too. I'll keep you update though

**Comment by eliteuser26** [comment]
I have made 2 suggestions to Metpy. When using morning soundings, should use the forecast afternoon temperature and dewpoint instead of the initial values to calculate severe weather indices. Also have a table of severe weather indices with the sounding.

**Comment by leifdenby** [comment]
Interesting. I think exposing the parameters for parcel calculation might be a good idea, that way it is more explicit. Maybe I will work towards that. It might be worth noting down what the scientific motivation would be for making different choices here, do you have something written down already? My background is more in large-eddy simulation modelling so I don't have much experience with using tephigrams in actual forecasting.

**Comment by eliteuser26** [comment]
I don't have anything written down just yet. I need to find out what is feasible with matplotlib and which severe weather indices to display. I do have a background in weather forecasting where we used tephigram on a regular basis. I am retired now but I retained that background. I intend to use it to be displayed on a web site which I need to create as well.
